config/routes.rb
Rails.application.routes.draw do

  get 'show_collectors' => 'monitors#show_collectors', as: :monitors_show_collectors
  get 'show_apis' => 'monitors#show_apis', as: :monitors_show_apis
  get 'monitors/index' => 'monitors#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monitors_controller.rb
class MonitorsController < ApplicationController
  include ResquesMonitor

  def show_apis
    @resque_data = ResquesMonitor.get_resque_data(ResqueMonitor.config.api_hosts)
    render action: :index
  end

  def show_collectors
    @resque_data = ResquesMonitor.get_resque_data(ResqueMonitor.config.collector_hosts)
    render action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monitors_helper.rb
module MonitorsHelper
  def host_name(name)
    if name.start_with?('23')
      result = "Staging API (#{name})"
    elsif name.start_with?('162.150.163.67')
      result = "CPG-Staging API (#{name})"
    elsif name.start_with?('54')
      result = "Production API (#{name})"
    elsif name.start_with?('162')
      result = "CPG-Production API (#{name})"
    elsif name.end_with?('8888')
      result = "Staging Collector (#{name})"
    elsif name.end_with?('8889')
      result = "Production Collector (#{name})"
    else
      result = name
    end
    link_to result, "http://#{name}/resque/overview", :target => '_blank'
  end
end

app/views/layouts/application.html.haml
!!!
%html{:lang => 'en'}
  %head
    %meta{:charset => 'utf-8'}/
    %meta{:content => 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible'}/
    %meta{:content => 'width=device-width, initial-scale=1.0', :name => 'viewport'}/
    %meta{content: 'yes', name: 'mobile-web-app-capable'}/
    %meta{content: 'yes', name: 'apple-mobile-web-app-capable'}/
    %title= content_for?(:title) ? yield(:title) : 'Resque Monitor'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
  %body
    #wrap
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            %a.btn.btn-navbar{'data-target' => '.nav-collapse', 'data-toggle' => 'collapse'}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to 'Resque Monitor', monitors_show_apis_path, class: 'brand'
            .container.nav-collapse
              %ul.nav
                %li.menu= link_to "API's", monitors_show_apis_path, role: 'button'
                %li.menu= link_to 'Collectors', monitors_show_collectors_path, role: 'button'
                -#%li.dropdown
                -#  = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', role: 'button' do
                -#    Reports
                -#    %b.caret
                -#  %ul.dropdown-menu{'aria-labelledby' => 'dashboards_dropdown', role: 'menu'}
                -#    %li.nav-header System Reports
                -#    %li= link_to 'Alarm History', '#', tabindex: '-1', role: 'menuitem'
                -#    %li= link_to 'Top Alarms', '#', tabindex: '-1', role: 'menuitem'

      .container-fluid
        .container
          .row
            .span12
              = notice_message
        .row-fixed
          .span12
            = yield

      #push

      #footer
        .container
          .pull-left.clocks= 'by-by'

app/views/monitors/index.html.haml
- @resque_data.each do |host|
  - host.each do |name, data|
    .row
      %h3= host_name(name)
      .queues_table.span4
        %h4 Queues
        %table.table.table-striped.table-hover.table-condensed.table-bordered
          %thead
            %tr
              %th Name
              %th Jobs

          %tbody
            - data[:queues].each do |queue|
              %tr
                %td= queue[0]
                %td= queue[1]



      .workers_table.span8
        %h4= data[:workers_title]
        %table.table.table-striped.table-hover.table-condensed.table-bordered
          %thead
            %tr
              %th Where
              %th Queue
              %th Processing
              %th

          %tbody
            - if data[:workers].blank?
              %tr
                %td Nothing is happening right now...
                %td
                %td
                %td
            - else
              - data[:workers].each do |worker|
                %tr
                  %td= worker[0]
                  %td= worker[1]
                  %td= worker[2]
                  %td
                    - time = Time.parse(worker[3])
                    - if Time.now.utc - time < 60
                      Just Now
                    - else
                      = time